name: List applications installed on a device.
command: "ns device list-applications"
tags:
  - ns
  - tns
  - nativescript
description: "Lists the installed applications on all connected Android and iOS devices."
source_url: "https://github.com/NativeScript/nativescript-cli/blob/master/docs/man_pages/device/device-list-applications.md"
author: erodriguezh
author_url: "https://github.com/erodriguezh"
shells: []
